---
title: "RNotebookExample"
date: "2024-02-12"
output: html_document
---

```{r load-data, message=FALSE}
#load tidyverse library
library(tidyverse) # used for data manipulation
library(rmarkdown) # used for paged_table function
library(kableExtra) # used for table
library(ggpubr) #used for ggarrange function 

#read file into R
pop_data <- read_csv("data/gapminder_data.csv")

#create a table with data from European countries in 2007 showing the countries 
#with the largest life expectancy at the top 
euro_data_tbl <- pop_data %>% 
                    filter(continent == "Europe" & year == 2007) %>% 
                    select(-continent, -year) %>% 
                    arrange(desc(lifeExp)) %>% 
                    rename(Country = country, "Population Size" = pop, 
                      "Life Expectancy" = lifeExp, "GDP" = gdpPercap)
    
```

```{r kbl, echo = FALSE}
euro_data_tbl %>% 
          kbl() %>%
          kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r paged-table}
paged_table(euro_data_tbl)
```

```{r}
euro_data_fig <- pop_data %>%
  filter(continent == "Europe")

euro_data_fig$year <- factor(euro_data_fig$year)

euro_plot <- ggplot(
  euro_data_fig,
  aes(x = year, y = lifeExp)) +
  geom_violin() +
  stat_summary(fun = median, geom = "point") +
  theme(axis.text.x = element_text(angle = 90))

euro_plot
```

```{r}
uk_data_fig <- pop_data %>%
  filter(country == "United Kingdom")

uk_data_fig$year <- factor(uk_data_fig$year)

uk_plot <- ggplot(
  uk_data_fig,
  aes(x = year, y = lifeExp)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90))

uk_plot
```

```{r}
ggarrange(euro_plot, uk_plot, ncol = 2, labels = c("A", "B"))
```